version: "3.2"
services:
  database:
    container_name: database
    # https://hub.docker.com/_/mysql
    image: mysql:5.7.30
    networks:
      - directus
    environment:
      MYSQL_ROOT_PASSWORD: secret-root
      MYSQL_DATABASE: directus
      MYSQL_USER: directus
      MYSQL_PASSWORD: secret-directus

      LANGL: C.UTF-8
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  directus:
    container_name: directus
    # https://hub.docker.com/r/directus/directus/tags?page=1&ordering=last_updated
    image: directus/directus:9.6.0
    ports:
      - "8080:8055"
    networks:
      - directus
    depends_on:
      - database
    environment:
      # https://docs.directus.io/configuration/config-options/
      PORT: "8055"
      PUBLIC_URL: "http://localhost:8080"
      LOG_LEVEL: info
      TELEMETRY: "false"

      KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
      SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263"

      DB_CLIENT: "mysql"
      DB_HOST: "database"
      DB_PORT: "3306"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "secret-directus"
      # DB_CHARSET: "UTF8_GENERAL_CI"

      ADMIN_EMAIL: "admin@example.org"
      ADMIN_PASSWORD: "secret-admin"

      AUTH_KEYCLOAK_ALLOW_PUBLIC_REGISTRATION: "true"
      AUTH_KEYCLOAK_CLIENT_ID: "log-directus"
      AUTH_KEYCLOAK_CLIENT_SECRET: "369ce95a-dc84-4277-8c68-a0b393aa14c8"
      AUTH_KEYCLOAK_DRIVER: "openid"
      AUTH_KEYCLOAK_IDENTIFIER_KEY: "sub"
      AUTH_KEYCLOAK_SCOPE: "openid email"
      AUTH_KEYCLOAK_REQUIRE_VERIFIED_EMAIL: "true"
      AUTH_KEYCLOAK_ISSUER_URL: "https://auth.bula21.ch/auth/realms/log-directus"

  adminer:
    image: michalhosna/adminer:4.8.0-en_v1
    environment:
      ADMINER_DB: directus
      ADMINER_SERVER: database
      ADMINER_USERNAME: directus
      ADMINER_PASSWORD: secret-directus
      ADMINER_DRIVER: server
      ADMINER_AUTOLOGIN: 1
      ADMINER_NAME: Directus

    ports:
      - 8081:8080
    networks:
      - directus
    depends_on:
      - database

  keycloak:
    image: jboss/keycloak:11.0.2
    ports:
      - 8082:8080
    volumes:
      - /opt/jboss/keycloak/standalone/data
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: secret-admin
      DB_VENDOR: h2

networks:
  directus:
