version: "3.2"
services:
  database:
    container_name: database
    # https://hub.docker.com/_/mysql
    image: mysql:5.7.30
    networks:
      - directus
    environment:
      MYSQL_ROOT_PASSWORD: secret-root
      MYSQL_DATABASE: directus
      MYSQL_USER: directus
      MYSQL_PASSWORD: secret-directus
    ports:
      - "3306:3306"

  directus:
    container_name: directus
    # https://hub.docker.com/r/directus/directus/tags?page=1&ordering=last_updated
    image: directus/directus:9.6.0
    ports:
      - "8080:8055"
    networks:
      - directus
    depends_on:
      - database
      - keycloak
    restart: always

    environment:
      # https://docs.directus.io/configuration/config-options/
      PORT: "8055"
      PUBLIC_URL: "http://localhost:8080"
      LOG_LEVEL: info
      TELEMETRY: "false"

      KEY: "255d861b-5ea1-5996-9aa3-922530ec40b1"
      SECRET: "6116487b-cda1-52c2-b5b5-c8022c45e263"

      DB_CLIENT: "mysql"
      DB_HOST: "database"
      DB_PORT: "3306"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "secret-directus"

      ADMIN_EMAIL: "admin@example.org"
      ADMIN_PASSWORD: "secret-admin"

      AUTH_PROVIDERS: "keycloak"
      AUTH_KEYCLOAK_ALLOW_PUBLIC_REGISTRATION: "true"
      AUTH_KEYCLOAK_CLIENT_ID: "log-directus"
      AUTH_KEYCLOAK_CLIENT_SECRET: "ada2ff6c-1d00-4458-91bc-c8f237805839"
      AUTH_KEYCLOAK_DRIVER: "openid"
      AUTH_KEYCLOAK_IDENTIFIER_KEY: "sub"
      AUTH_KEYCLOAK_SCOPE: "openid profile email roles"
      AUTH_KEYCLOAK_REQUIRE_VERIFIED_EMAIL: "true"
      AUTH_KEYCLOAK_ISSUER_URL: "http://keycloak:8082/auth/realms/log-directus"
      # AUTH_KEYCLOAK_DEFAULT_ROLE_ID # TODO

  adminer:
    image: michalhosna/adminer:4.8.0-en_v1
    environment:
      ADMINER_DB: directus
      ADMINER_SERVER: database
      ADMINER_USERNAME: directus
      ADMINER_PASSWORD: secret-directus
      ADMINER_DRIVER: server
      ADMINER_AUTOLOGIN: 1
      ADMINER_NAME: Directus

    ports:
      - 8081:8080
    networks:
      - directus
    depends_on:
      - database

  keycloak:
    image: jboss/keycloak:11.0.2
    ports:
      - 8082:8082
    networks:
      - directus
    volumes:
      - /opt/jboss/keycloak/standalone/data
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: secret-admin
      DB_VENDOR: h2
    command: "-Djboss.http.port=8082"

networks:
  directus:
